---
abstract: 'Data Mining Open Source Software'
author:
  - 'Nuno Carvalho <smash@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DMOSS
requires:
  Archive::Extract: 0
  Data::Dumper: 0
  File::Basename: 0
  File::Comments: 0
  File::Copy: 0
  File::Fetch: 0
  File::Find: 0
  File::Path: 0
  File::Slurp: 0
  HTML::FormatText::Html2text: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  Lingua::Identify: 0
  Module::Find: 0
  Software::License: 0
  Software::LicenseUtils: 0
  Storable: 0
  Text::Aspell: 0
  URI::Find: 0
  parent: 0
  strict: 0
  warnings: 0
version: 0.01_1
